#!/usr/bin/env python
#  ./scrambled-strings --dictionary lololo --input lalala

import sys, getopt
from the_files import TheFiles

def main(argv):
   dictionary = ''
   input = ''
   try:
      opts, args = getopt.getopt(argv,"",["dictionary=","input="])
      if len(opts) != 2:
          print("Correct format: ./scrambled-strings --dictionary <dictionary_file> --input <input_file>")
          sys.exit()
   except getopt.GetoptError:
      print("Correct format: ./scrambled-strings --dictionary <dictionary_file> --input <input_file>")
      sys.exit()

   the_files = TheFiles(opts)
   # the_files.validate_dict()
   dictionary = the_files.dictionary
   input = the_files.input


   print(dictionary)
   print('input file is ' + input)

if __name__ == "__main__":
   main(sys.argv[1:])