#!/usr/bin/env python
#  ./scrambled-strings --dictionary Files/dictionary1 --input Files/input1

import sys, getopt
from the_files import TheFiles
from scrambled_words import ScrambledWords

def main(argv):

   try:
      opts, args = getopt.getopt(argv,"",["dictionary=","input="])
      if len(opts) != 2:
          print("Correct format: ./scrambled-strings --dictionary <dictionary_file> --input <input_file>")
          sys.exit()
   except getopt.GetoptError:
      print("Correct format: ./scrambled-strings --dictionary <dictionary_file> --input <input_file>")
      sys.exit()

   the_files = TheFiles(opts)
   # the_files.validate_dict()
   dictionary = the_files.dictionary
   input = the_files.input
   a = ScrambledWords(dictionary,input)
   a.get_scrambled_words_occurences()


if __name__ == "__main__":
   main(sys.argv[1:])